[package]
org = "ballerina"
name = "random"
version = "@toml.version@"
authors = ["Ballerina"]
keywords = ["pseudo-random"]
repository = "https://github.com/ballerina-platform/module-ballerina-random"
license = ["Apache-2.0"]
distribution = "slbeta3"

[[platform.java11.dependency]]
path = "../native/build/libs/random-native-@project.version@.jar"
