[package]
org = "ballerina"
name = "random"
version = "1.2.0"
authors = ["Ballerina"]
keywords = ["pseudo-random"]
repository = "https://github.com/ballerina-platform/module-ballerina-random"
license = ["Apache-2.0"]
distribution = "2201.0.0"

[[platform.java11.dependency]]
path = "../native/build/libs/random-native-1.2.0-SNAPSHOT.jar"
