[package]
org = "ballerina"
name = "random"
version = "1.2.2"
authors = ["Ballerina"]
keywords = ["pseudo-random"]
repository = "https://github.com/ballerina-platform/module-ballerina-random"
icon = "icon.png"
license = ["Apache-2.0"]
distribution = "2201.0.1"
